Dev branch 1
SatyenderSinghRana/Omnical pull request #1
Opened 2021-06-03 11:59 UTC by SatyenderSinghRana

2021-06-03 15:05 UTC, Veradux requested changes
I mostly pointed out minor things, as a start. So that you can get a hang of the pull request review process. 

I didn't really go that in depth into the calculator logic, because I already spent a lot of time on this and I don't really have much time left today. But I would definitely like to do that too some other time.

2021-06-03 15:05 UTC, Veradux commented on app/src/main/res/values/strings.xml
> +    <string name="button_right_bracket">)</string>
Instead of having constants in the java code, AND having string resources here, you can actually use these strings in the code in the activities as well in place of the constants, like this:
```java
private final String rightBracket = this.getString(R.string.button_right_bracket);
```

This way, there's even less duplication of these values!

2021-06-03 15:14 UTC, SatyenderSinghRana commented on app/src/test/java/com/example/omnical/ExampleUnitTest.java
> +    }//add, commit, push, pull, fetch origin, cherry pick, merge, rebase
Haha, I'll remove it

2021-06-03 15:41 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +        if (!firstRun) {
I intended to display the splash screen once when user installs the app. After first install the calculator opens directly. If other modules like convertor, account manager, custom formula are added, then some explanation can be given after the splash screen loads, the first time user installs the app.

2021-06-03 15:57 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +            }, 1000);
I've added a reminder to modify the splash screen later.

2021-06-03 15:58 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +            }, 1000);
I've replaced it with a splashScreenDuration.

2021-06-03 16:02 UTC, SatyenderSinghRana commented on app/src/main/res/layout/activity_main.xml
> +    //Top area
I've fixed the comments and removed tools:ignore="ExtraText".

2021-06-03 16:06 UTC, SatyenderSinghRana commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintGuide_percent="0.756691" />
Yeah, I used guidelines for the first time and I used the visual editor to add them. I've modified the values and I'll try to do most of my work by writing the xml code.

2021-06-03 16:44 UTC, SatyenderSinghRana commented on app/src/main/res/values/strings.xml
> +    <string name="button_right_bracket">)</string>
I have replace all the constants in the java code.

2021-06-04 11:19 UTC, Veradux requested changes

2021-06-04 11:19 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    private String spAnswer = "ANSWER";
These two fields never change, right? They should always stay the same. So they should be constants. A constant means that a value is final. Final means that you can't change the value of the field. 

And if you want to use the constants in another class, the constant should also be static, but this is not necessary right now because you don't have to use them anywhere else. Have you heard about the static keyword?

Also, spAnswer doesn't mean anything to me when I look at it. I have no immediate idea what sp is. The name can be a lot better. And when you are making constants, their name should be in capital letters, here's an example:

```java
private final String ANSWER_PREFS_KEY = "ANSWER";
```

2021-06-04 11:19 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>          });
This is still not updated the way I requested in the previous comment.

2021-06-04 11:19 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    //Take the expressiion and divide it into tokens
This is still not updated.

2021-06-04 11:19 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +*/
I explained in another comment how to write documentation. You can update this comment to that way as well.

2021-06-04 11:23 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +*/
I've changed it.

2021-06-04 11:34 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> -    }
Thanks.

2021-06-04 11:42 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +        binding.btnDel.animate().translationZ(6);
I have removed the properties related to animation as it is not needed anymore but I'll focus more on naming conventions and code reusability.

2021-06-04 11:54 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    private String spAnswer = "ANSWER";
I have added static final to both expression and answer. Static means that the variable or method can be accessed globally, right?
I have added SonarLint plugin to my Android Studio, so when I use this naming convention "ANSWER_PREFS_KEY"
I get this warning: Field names should comply with a naming convention
Noncompliant Code Example: private int my_field;
Compliant Solution: private int myField;

Is it okay if I use answerPrefsKey or should I use ANSWER_PREFS_KEY?

2021-06-04 12:01 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>                  if (s.length() != 0) {
isEmpty() is not working as "s" is of type CharSequence, for now, I have left it unchanged.

2021-06-04 12:04 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>          if (!expression.equals("")) {
I have changed it.

2021-06-04 12:14 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>              }
Oh yeah, thanks for mentioning it. I have changed all the numbers and operators with String values, you can review them in the next commit/push. If you meant a change in terms of implementation then I'll try to come up with a better way to implement this section of code.

2021-06-04 12:15 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>              if (expression.endsWith(")")) {
I have changed them now.

2021-06-04 12:15 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +        binding.btnDivide.setOnClickListener(v -> checkOperator("/"));
Also changed these.

2021-06-04 12:25 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    //Take the expressiion and divide it into tokens
"Hold Control + left mouse click" was really cool feature :D
I applied this way of commenting for SplashActivity.java.
In the case of single-line comments, I just used "ctrl + /", if it's not implemented properly I'll change it.

2021-06-04 12:43 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    private String spAnswer = "ANSWER";
> Static means that the variable or method can be accessed globally, right?

You know how variables are attached to the objects? For example, every time you create an object of MainActivity, they all have their own copies of the variables:
```java 
private MainActivity firstObject = new MainActivity();
private MainActivity secondObject = new MainActivity();

firstObject.variable = 5;
boolean isSecondVariableTheSame = secondObject.variable == 5;
```
<details>
<summary>Do you think isSecondVariableTheSame is true? Click on this to see the answer. :D </summary>
It's false. When you change a variable, it only changes for the object the variable belongs to. I think you know this already but I'm making sure it's clear.
</details>

So! Variables are attached to objects, right? Well, in Java you can instead make variables which are attached to the class! That's what static does. It creates only one variable for the entire class. 

That also means that you do not require an object of this class to access the variable. You can just do this:

```java 
MainActivity.sharedPrefsKey = 5;
```

Let's say we have the class Dog.
The reason why the static keyword is important too is because if you need to create thousands or millions of dogs, the static variable will still be only one, because there is only one Dog class. This in your current case with MainActivity does not matter much, which is also why I said this in the first comment:
> the constant should also be static, but this is not necessary right now

You don't really need to make anything static so far, it won't make that big of a difference because you don't have to access this field in a lot of places. But knowing about it is good, that's why I mentioned it and explained it.

2021-06-04 12:45 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    //Take the expressiion and divide it into tokens
I've fixed it. I'll definitely not repeat these silly mistakes.

2021-06-04 12:45 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>              }
I mean implementation, yes something is repeating here, and it can look a lot nicer.

2021-06-04 12:46 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>          answer = sharedPrefs.getString("ANSWER", "");
I've fixed it.

2021-06-04 12:48 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>          });
I have fixed them, I was going to push them all together.

2021-06-04 12:48 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    //Take the expressiion and divide it into tokens
Spelling mistakes happen al lthe time to everyone, don't worry about it

2021-06-04 12:52 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    private String spAnswer = "ANSWER";
> Static means that the variable or method can be accessed globally, right?
Also, if the static variable is set ot private, you won't be able to access it globally. Access is related to the access modifiers, private, protected, and public. Static is about the variable being one per class, or one per object.

2021-06-04 12:54 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
>              }
Okay, I'll see what I can do :)

2021-06-04 12:55 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    //Take the expressiion and divide it into tokens
XD Yeah but if unchecked it can be desasterus

2021-06-04 13:31 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    private String spAnswer = "ANSWER";
Okay, I've learned so many new things here.

2021-06-13 11:31 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +        String PASSED_VALUE = view.getTag().toString();
This variable's name shouldn't be with capital letters. Capital letters are for constants. They signify that a value cannot be changed, that it always stays the same. And that it's declared in the beginning of runtime. You do that by using the keyword `final`, and `static` if you need to.

2021-06-13 11:31 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +        String PASSED_VALUE = view.getTag().toString();
An example of a constant value is pi in math. It's always 3.14. You can't change pi, and you shouldn't change pi. Like how your "(" value is a constant and it's called RIGHT_PARENTHESIS. You will never need to change that to be another symbol.

Whereas this passed value on line 124 is user input, you will never know what the value will be.

2021-06-13 11:31 UTC, Veradux commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    public void buttonPressed(View view) {
This whole method looks kinda crazy, you will benefit from splitting it into smaller methods, one method for each type of operation.

2021-06-13 12:30 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +            final int splashScreenDuration = 1000;
Ok, I'll declare constants like this in the future.

2021-06-13 12:31 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/SplashActivity.java
> +        final float TRANSLATION_Y_VALUE = 0f;
I'll fix these also.

2021-06-13 12:33 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +        String PASSED_VALUE = view.getTag().toString();
Ok, fixed this also.

2021-06-13 13:40 UTC, SatyenderSinghRana commented on app/src/main/java/com/calculator/omnical/MainActivity.java
> +    public void buttonPressed(View view) {
I've divided them into individual methods.

2021-06-13 17:52 UTC, merged